"""create research collaborations

Revision ID: de3884ada680
Revises: 6057488aa35f
Create Date: 2026-08-06 14:08:55.630348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de3884ada680'
down_revision: Union[str, Sequence[str], None] = '6057488aa35f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_collaborations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('researcher1_id', sa.UUID(), nullable=False),
    sa.Column('researcher2_id', sa.UUID(), nullable=False),
    sa.Column('publication_id', sa.UUID(), nullable=True),
    sa.Column('collaboration_type', sa.Enum('COAUTHOR', 'PROJECT', 'SUPERVISION', 'FUNDING', 'OTHER', name='collaborationtype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'PENDING', name='collaborationstatus'), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['researcher1_id'], ['researchers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['researcher2_id'], ['researchers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('notifications')
    op.drop_table('collaborations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('receiver_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('collaborations_receiver_id_fkey')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('collaborations_sender_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('collaborations_pkey'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('notification_type', postgresql.ENUM('COLLABORATION', 'CONFERENCE', 'PUBLICATION', 'SYSTEM', name='notificationtype'), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.drop_table('research_collaborations')
    # ### end Alembic commands ###
