"""recreate researcher schema

Revision ID: fecc1ecc3773
Revises: 238281789a81
Create Date: 2026-07-23 14:14:44.489317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fecc1ecc3773'
down_revision: Union[str, Sequence[str], None] = '238281789a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researchers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('orcid', sa.String(length=50), nullable=True),
    sa.Column('google_scholar', sa.String(length=500), nullable=True),
    sa.Column('research_gate', sa.String(length=500), nullable=True),
    sa.Column('linkedin', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('experience >= 0', name='ck_experience_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orcid', name='uq_researcher_orcid'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('publication_authors',
    sa.Column('publication_id', sa.UUID(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('author_order', sa.Integer(), nullable=False),
    sa.Column('is_corresponding_author', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('publication_id', 'researcher_id')
    )
    op.create_table('researcher_departments',
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('researcher_id', 'department_id')
    )
    op.alter_column('publications', 'citation_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('publications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('publications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('publications_doi_key'), 'publications', type_='unique')
    op.create_unique_constraint('uq_publication_doi', 'publications', ['doi'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_publication_doi', 'publications', type_='unique')
    op.create_unique_constraint(op.f('publications_doi_key'), 'publications', ['doi'], postgresql_nulls_not_distinct=False)
    op.alter_column('publications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('publications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('publications', 'citation_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_table('researcher_departments')
    op.drop_table('publication_authors')
    op.drop_table('researchers')
    # ### end Alembic commands ###
